### PR TITLE
[Do-Not-Merge] Confluent specific changes on top of 24.0.0 (RC1)

### PR DESCRIPTION
**Pull request by kkonstantine**
Fixes #XXXX.

#### Added a forbidden-apis entry ...

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by lokesh-lingarajan** [comment]
@kkonstantine - I dont think we need the following commit any more https://github.com/confluentinc/druid/pull/108/commits/99a6e6a50cafaa8c808d4ffa9fd7b51e4ceb2e7c 

as 24.0 branch already this changelist

**Comment by kkonstantine** [comment]
> @kkonstantine - I dont think we need the following commit any more [99a6e6a](https://github.com/confluentinc/druid/commit/99a6e6a50cafaa8c808d4ffa9fd7b51e4ceb2e7c)
> 
> as 24.0 branch already this changelist

@lokesh-lingarajan, as you can see in the commit link, the only changes that this commit bring are some documentation changes in: `docs/ingestion/data-formats.md`. 

The rest of the changes have been adopted from upstream. 

Are you suggesting that we should discard these doc changes by removing commit https://github.com/confluentinc/druid/commit/99a6e6a50cafaa8c808d4ffa9fd7b51e4ceb2e7c altogether from this PR?

**Comment by lokesh-lingarajan** [comment]
> > @kkonstantine - I dont think we need the following commit any more [99a6e6a](https://github.com/confluentinc/druid/commit/99a6e6a50cafaa8c808d4ffa9fd7b51e4ceb2e7c)
> > as 24.0 branch already this changelist
> 
> @lokesh-lingarajan, as you can see in the commit link, the only changes that this commit bring are some documentation changes in: `docs/ingestion/data-formats.md`.
> 
> The rest of the changes have been adopted from upstream.
> 
> Are you suggesting that we should discard these doc changes by removing commit [99a6e6a](https://github.com/confluentinc/druid/commit/99a6e6a50cafaa8c808d4ffa9fd7b51e4ceb2e7c) altogether from this PR?

Thats correct @kkonstantine, 24.0 branch has the documented changes as well.

**Comment by xvrl** [comment]
can we close this @kkonstantine ?

**Comment by kkonstantine** [comment]
Indeed. We have upgraded.

**Pull request closed without merging**
