### PR TITLE
Fixing checkstyle issues in opencensus and opentelemetry extensions.

### PR DESCRIPTION
**Pull request by harinirajendran**

### CODE REVIEW

**Review by xvrl — APPROVED** [review]
LGTM once the build passes

**Comment by harinirajendran** [comment]
> LGTM once the build passes

@xvrl Can you give a +1 again? Had missed a couple fixes earlier.

**Comment by harinirajendran** [comment]
@xvrl : Build passed except one flaky test
https://confluentinc.semaphoreci.com/workflows/411b7614-a2d5-414c-97b6-e372bae2f95b?pipeline_id=c49dde08-853e-43b2-98a3-25dceddd9112
Can you approve this?

**Review by xvrl — APPROVED** [review]
we can ignore the flaky test

**Pull request merged**
