### PR TITLE
Setting default query lane from druid console.

### PR DESCRIPTION
**Pull request by harinirajendran**
Setting default `lane` in query context for queries made from Druid console.

### CODE REVIEW

**Review by Zohimi — COMMENTED** [review]
How is this label used? only for logging? or, also in laning?

**Comment by arrawatia** [comment]
@harinirajendran what would it take to make it configurable ? That way we can change this when we refine the query laning strategy even more later.

**Comment by harinirajendran** [comment]
> @harinirajendran what would it take to make it configurable ? That way we can change this when we refine the query laning strategy even more later.

Since this is a part of web-console config and we don't configure anything wrt today, I didn't spend a lot of time looking into it. If we are in a state where we start making frequent updates to this, I think at that point we can dig a bit further.

**Review by arrawatia — APPROVED** [review]
I did a quick dive through the code and issues to see if there was a easy mechanism to make this configurable but I did not find anything.

Lets merge this and figure out how to make it configurable later.

**Pull request merged**
